# Generated by Django 3.2.13 on 2022-05-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('number', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=11, unique=True)),
                ('phonetype', models.IntegerField(choices=[('1', 'Landline phone'), ('0', 'Mobile phone')])),
                ('phone1', models.DecimalField(blank=True, decimal_places=0, max_digits=11)),
                ('phonetype1', models.IntegerField(blank=True, choices=[('1', 'Landline phone'), ('0', 'Mobile phone')])),
                ('agency', models.CharField(max_length=250)),
                ('agency_name', models.CharField(max_length=250)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
            options={
                'db_table': 'Agency',
            },
        ),
    ]
