# Generated by Django 3.2.13 on 2022-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone1',
            field=models.BigIntegerField(blank=True),
        ),
    ]
