# Generated by Django 3.2.13 on 2022-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20220524_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phonetype',
            field=models.IntegerField(blank=True, choices=[('1', 'Landline phone'), ('0', 'Mobile phone')]),
        ),
    ]
