version: '3.8'

services:

  fastapi:
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    container_name: fastAPI
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - default
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: fastapi_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi
    networks:
      - default
    ports:
      - 80:80
  
  db:
    image: postgres:12.4-alpine
    container_name: postgresfastapi
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5455:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin1234"
    ports:
      - "15432:80"
    depends_on:
      - postgres

volumes:
  fastapiw:
    external: true


    

