version: '3.8'

services:

  django:
    build: .
    container_name: web
    restart: always
    command: sh -c "python manage.py collectstatic --no-input && gunicorn app.wsgi:application -b 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /app/static:/static
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - /app/static:/static
    ports:
      - "8000:8000"
    depends_on:
      - django

  
  db:
    image: postgres:13
    container_name: postgresdjango
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 2s
      timeout: 3s
      retries: 10

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin1234"
    ports:
      - "15432:80"
    depends_on:
      - db
  



volumes:
  postgres-data:
    external: true
    




    

