version: '3.8'

services:

  django:
    build: .
    container_name: webdjango
    command: "gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload"
    env_file:
      - .env
    volumes:
      - ./app:/app/
    ports:
      - "3000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django

  
  db:
    image: postgres:12.4-alpine
    container_name: postgresdjango
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
    external: true



    

