version: '3.8'

services:

  fastapi:
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    container_name: fastAPI
    environment:
      MONGODB_DATABASE: fastapidb
      MONGODB_USERNAME: fastapiuser
      MONGODB_PASSWORD: 1234
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./app:/app
    networks:
      - default
    depends_on:
      - mongodb

  nginx:
    image: nginx:stable-alpine
    container_name: fastapi_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi
    networks:
      - default
    ports:
      - 80:80
  
  mongodb:
    image: mongo
    container_name: mongodb_web
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: fastapidb
    volumes:
      - fastapiw:/data/db
    ports:
      - 27017:27017
    networks:
      - default

volumes:
  fastapiw:
    external: true


    

