version: '3.8'

services:

  fastapi:
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    container_name: fastAPI
    volumes:
      - ./app:/app
    networks:
      - default
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: fastapi_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - fastapi
    networks:
      - default
    ports:
      - 80:80
  
  db:
    image: phdcoder/postgresbr
    restart: always
    volumes:
      - fastapiw:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: fastapiweb
      POSTGRES_DB: progweb
      POSTGRES_PASSWORD: web1
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5455:5432"



volumes:
  fastapiw:
    external: true


    

