# Generated by Django 3.2.13 on 2022-06-22 12:46

import banco.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True, validators=[banco.validators.nome_validator])),
                ('numero', models.CharField(max_length=250, null=True, unique=True)),
            ],
            options={
                'db_table': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('fone', models.BigIntegerField(blank=True, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('0', 'Fixo'), ('1', 'Celular')], max_length=1)),
                ('fone1', models.BigIntegerField(blank=True)),
                ('tipo1', models.CharField(blank=True, choices=[('0', 'Fixo'), ('1', 'Celular')], max_length=1)),
                ('agencia', models.CharField(max_length=100)),
                ('nome_agencia', models.CharField(max_length=100)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.banco', verbose_name='idBanco')),
            ],
            options={
                'db_table': 'Agencia',
            },
        ),
    ]
