# Generated by Django 3.2.13 on 2022-05-25 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('numero', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'Banco',
            },
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=250)),
                ('fone', models.BigIntegerField(blank=True, unique=True)),
                ('tipo', models.IntegerField(blank=True, choices=[('1', 'Fixo'), ('0', 'Celular')])),
                ('fone1', models.BigIntegerField(blank=True)),
                ('tipo1', models.IntegerField(blank=True, choices=[('1', 'Fixo'), ('0', 'Celular')])),
                ('agencia', models.CharField(max_length=250)),
                ('nome_agencia', models.CharField(max_length=250)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.banco')),
            ],
            options={
                'db_table': 'Agencia',
            },
        ),
    ]
