# Generated by Django 3.2.13 on 2022-06-08 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='fone1',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.IntegerField(choices=[('1', 'Fixo'), ('0', 'Celular')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.IntegerField(blank=True, choices=[('1', 'Fixo'), ('0', 'Celular')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
