# Generated by Django 3.2.13 on 2022-05-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencia',
            table='agencia',
        ),
        migrations.AlterModelTable(
            name='banco',
            table='banco',
        ),
    ]
