# Generated by Django 3.2.13 on 2022-06-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='agencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='fone',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nome_agencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('0', 'Fixo'), ('1', 'Celular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.CharField(blank=True, choices=[('0', 'Fixo'), ('1', 'Celular')], max_length=1),
        ),
    ]
