# Generated by Django 3.2.13 on 2022-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Fixo'), (0, 'Celular')]),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.IntegerField(blank=True, choices=[(1, 'Fixo'), (0, 'Celular')]),
        ),
    ]
