# Generated by Django 3.2.13 on 2022-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='fone',
            field=models.BigIntegerField(blank=True, unique=True, verbose_name='Telefone'),
        ),
    ]
