# Generated by Django 3.2.13 on 2022-05-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20220517_1957'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agencia',
            table='Agencia',
        ),
        migrations.AlterModelTable(
            name='banco',
            table='Banco',
        ),
    ]
