# Generated by Django 3.2.13 on 2022-06-01 13:46

import banco.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_alter_banco_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='numero',
            field=models.CharField(max_length=250, unique=True, validators=[banco.validators.numero_validator]),
        ),
    ]
