# Generated by Django 3.2.13 on 2022-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20220608_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.CharField(choices=[('1', 'Fixo'), ('0', 'Celular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.IntegerField(blank=True, choices=[('1', 'Fixo'), ('0', 'Celular')], max_length=1),
        ),
    ]
