# Generated by Django 3.2.13 on 2022-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_auto_20220608_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.BooleanField(choices=[('true', 'Fixo'), ('false', 'Celular')]),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.BooleanField(blank=True, choices=[('true', 'Fixo'), ('false', 'Celular')]),
        ),
    ]
