# Generated by Django 3.2.13 on 2022-06-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_auto_20220608_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Fixo'), (1, 'Celular')]),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.IntegerField(blank=True, choices=[(0, 'Fixo'), (1, 'Celular')]),
        ),
    ]
