# Generated by Django 3.2.13 on 2022-06-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_auto_20220608_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Celular'), (0, 'Fixo')]),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.IntegerField(blank=True, choices=[(1, 'Celular'), (0, 'Fixo')]),
        ),
    ]
