# Generated by Django 3.2.13 on 2022-05-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_auto_20220518_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='fone',
            field=models.DecimalField(decimal_places=0, max_digits=11, unique=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='fone1',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.IntegerField(blank=True, choices=[('1', 'Fixo'), ('0', 'Celular')]),
        ),
    ]
