# Generated by Django 3.2.13 on 2022-06-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_auto_20220608_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.CharField(choices=[('f', 'Fixo'), ('c', 'Celular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.BooleanField(choices=[('f', 'Fixo'), ('c', 'Celular')], max_length=1),
        ),
    ]
