# Generated by Django 3.2.13 on 2022-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_auto_20220608_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('0', 'Fixo'), ('1', 'Celular')], max_length=1),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='tipo1',
            field=models.CharField(blank=True, choices=[('0', 'Fixo'), ('1', 'Celular')], max_length=1),
        ),
    ]
