# Generated by Django 3.2.13 on 2022-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_alter_agencia_tipo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='fone1',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
